---
title: "likert chart"
output:
  html_document: default
  pdf_document: default
date: '2022-03-28'
---

## import library
```{r setup likert}
library(likert)
```

## Import data

```{r}
rawdata <- read_csv("~/data.csv")
```

##delete first and second row
```{r data cleansing}
data <- data[-c(1:2),]
```

## Create Age columns

```{r create age columns}
data$age <- 2022 - as.numeric(data$birthyear)
```

## Create Age groups

```{r create age groups}
data["age_group"] = cut(data$age, c(18, 44, 49, 64, Inf), c("18-44", "45-49", "50-64", ">64"), include.lowest=TRUE)
```

## Extract columns from data

```{r}
whenready <- data[c("age_group","whenready_1","whenready_2","whenready_3","whenready_4","whenready_5","whenready_6","whenready_7","whenready_8","whenready_9","whenready_10")]
```

## create levels

```{r create levels}
levels = c("I am already ready or doing it","In 1-4 months","In 4-6 months","In more than 6 months","When a vaccine will be ready or the virus will have disappeared","I don’t foresee a time when I will be ready to do it again","Not applicable for me")
```

##  Change Likert scores to factor and specify levels

```{r change likert scores}
whenready$whenready_1 = factor(whenready$whenready_1,levels,ordered = TRUE)
whenready$whenready_2 = factor(whenready$whenready_2,levels,ordered = TRUE)
whenready$whenready_3 = factor(whenready$whenready_3,levels,ordered = TRUE)
whenready$whenready_4 = factor(whenready$whenready_4,levels,ordered = TRUE)
whenready$whenready_5 = factor(whenready$whenready_5,levels,ordered = TRUE)
whenready$whenready_6 = factor(whenready$whenready_6,levels,ordered = TRUE)
whenready$whenready_7 = factor(whenready$whenready_7,levels,ordered = TRUE)
whenready$whenready_8 = factor(whenready$whenready_8,levels,ordered = TRUE)
whenready$whenready_9 = factor(whenready$whenready_9,levels,ordered = TRUE)
whenready$whenready_10 = factor(whenready$whenready_10,levels,ordered = TRUE)
```

## Create likert plot

```{r create likert plot}
whenready_plot <- whenready[c("whenready_1","whenready_2","whenready_4","whenready_4","whenready_5","whenready_6","whenready_7","whenready_8","whenready_9","whenready_10")]
colnames(whenready_plot) <- c("Travel domestically by plane for business or essential purposes","Travel internationally by plane for business or essential purposes","Travel domestically by plane for leisure","Travel internationally by plane for leisure","Go shopping in-person at stores or malls","Return to the workplace","Go eat in restaurants","Go to bars, clubs, or crowded spaces","Attend large public events like a festival or outdoor gathering","Take public transit")
results <- likert(as.data.frame(whenready_plot))
title1 <- "Perceptions of post-covid behaviours"
summary(results)
plot<- plot(results)
final_plot <- plot + ggtitle(title1)
final_plot
```
## Create likert plot by age groups and separate into two groups of question themes - travel and local activity

```{r create likert plots by groups}
colnames(whenready) <- c("age_group","Travel domestically by plane for business or essential purposes","Travel internationally by plane for business or essential purposes","Travel domestically by plane for leisure","Travel internationally by plane for leisure","Go shopping in-person at stores or malls","Return to the workplace","Go eat in restaurants","Go to bars, clubs, or crowded spaces","Attend large public events like a festival or outdoor gathering","Take public transit")
cluster_plot_travel <- plot(likert(as.data.frame(whenready[,2:5]),grouping = whenready$age_group)) + ggtitle("Perceptions of post-covid behaviours - travel")
cluster_plot_travel
cluster_plot_activity <- plot(likert(as.data.frame(whenready[,6:11]),grouping = whenready$age_group)) + ggtitle("Perceptions of post-covid behaviours - local activity")
cluster_plot_activity
```
